package main

import (
	"encoding/json"
	"errors"
	"fmt"
	fiberlog "github.com/gofiber/fiber/v2/log"
	"github.com/pion/interceptor"
	"github.com/pion/interceptor/pkg/intervalpli"
	"io"
	"log"

	"github.com/gofiber/contrib/websocket"
	"github.com/gofiber/fiber/v2"
	"github.com/gofiber/fiber/v2/middleware/recover"
	"github.com/pion/webrtc/v4"
	"robot/signal"
)

//type WsMessage2 struct {
//	ClientId string `json:"c,omitempty"`
//	RobotId  string `json:"r,omitempty"`
//	Body     Body   `json:"body,omitempty"`
//}
//
//type Body struct {
//	Action string `json:"action,omitempty"`
//	Button string `json:"button,omitempty"`
//	Base64 string `json:"data,omitempty"`
//}

type WsMessage struct {
	Action   string `json:"action,omitempty"`
	Button   string `json:"button,omitempty"`
	ClientId string `json:"c,omitempty"`
	RobotId  string `json:"r,omitempty"`
	Base64   string `json:"data,omitempty"`
}

type Data struct {
	Base64 string `json:"data,omitempty"`
}

var connections = make(map[string]*websocket.Conn)
var robots = make(map[string]string)
var users = make(map[string]string)

func main() {
	app := fiber.New()

	app.Use(recover.New())

	app.Use("/websocket", func(c *fiber.Ctx) error {
		fiberlog.Info("websocket check origin")
		return c.Next()
		//if c.Get("host") == "localhost:9097" {
		//	c.Locals("Host", "Localhost:9097")
		//	return c.Next()
		//}
		//return c.Status(403).SendString("Request origin not allowed middleware")
	})

	app.Get("/websocket", websocket.New(func(conn *websocket.Conn) {
		fiberlog.Info(conn.Locals("Host")) // "Localhost:3000"
		for {
			mt, msg, err := conn.ReadMessage()
			if err != nil {
				log.Println("read:", err)
				break
			}

			log.Printf("recv: %s", msg)

			message := WsMessage{}
			err = json.Unmarshal(msg, &message)

			if err != nil {
				log.Println("error:", err)
				return
			}

			if message.Action != "" && message.Button != "" && message.ClientId != "" {
				log.Println("Move")
				robotId := users[message.ClientId]

				if robotId != "" {
					roboClient := connections[robotId]
					roboClient.WriteMessage(mt, msg)
				}

			} else if message.RobotId != "" {
				fiberlog.Info("Robot Connected:", message.RobotId)
				connections[message.RobotId] = conn
				robots[message.RobotId] = ""

				for userId, robotId := range users {
					if robotId == "" {
						robots[message.RobotId] = userId
						users[userId] = message.RobotId
						break
					}
				}

			} else if message.ClientId != "" {
				for robotId, userId := range robots {
					log.Printf("userId: %s, robotId: %s", userId, robotId)

					if userId == "" {
						users[message.ClientId] = robotId
						robots[message.RobotId] = message.ClientId
						connections[message.RobotId] = conn
						log.Println("User assigned to the robot")
						break
					} else {
						log.Println("This robot is not available")
					}
				}
			}

			//err = conn.WriteMessage(mt, msg)
			//
			//if err != nil {
			//	log.Println("write:", err)
			//	break
			//}
		}
	}))
	app.Options("/stream", func(ctx *fiber.Ctx) error {
		ctx.Accepts("Access-Control-Allow-Methods", "POST")
		ctx.Accepts("Allow", "OPTIONS, GET, HEAD, POST")

		return ctx.Send([]byte(""))
	})

	app.Post("/stream", func(ctx *fiber.Ctx) error {

		fmt.Println("start stream ")

		data := new(Data)

		if err := ctx.BodyParser(data); err != nil {
			return err
		}

	})

	app.Static("/", "./ui/dist/")
	app.Static("/*", "./ui/dist/index.html")

	chanData := make(chan Data{Base64: "",})

	go broadcast(chanData)

	//streamApp := fiber.New()
	//streamApp.Listen(":9090")

	log.Fatal(app.Listen(":9097"))
}

func broadcast(base64 chan string) {
	offer := webrtc.SessionDescription{}

	signal.Decode(<-base64, &offer)

	fmt.Printf("%v", offer, offer)

	peerConnectionConfig := webrtc.Configuration{
		ICEServers: []webrtc.ICEServer{
			{
				URLs: []string{"stun:stun.l.google.com:19302"},
			},
		},
	}

	m := &webrtc.MediaEngine{}
	if err := m.RegisterDefaultCodecs(); err != nil {
		panic(err)
	}

	// Create a InterceptorRegistry. This is the user configurable RTP/RTCP Pipeline.
	// This provides NACKs, RTCP Reports and other features. If you use `webrtc.NewPeerConnection`
	// this is enabled by default. If you are manually managing You MUST create a InterceptorRegistry
	// for each PeerConnection.
	i := &interceptor.Registry{}

	// Use the default set of Interceptors
	if err := webrtc.RegisterDefaultInterceptors(m, i); err != nil {
		panic(err)
	}

	// Register a intervalpli factory
	// This interceptor sends a PLI every 3 seconds. A PLI causes a video keyframe to be generated by the sender.
	// This makes our video seekable and more error resilent, but at a cost of lower picture quality and higher bitrates
	// A real world application should process incoming RTCP packets from viewers and forward them to senders
	intervalPliFactory, err := intervalpli.NewReceiverInterceptor()
	if err != nil {
		panic(err)
	}
	i.Add(intervalPliFactory)

	// Create a new RTCPeerConnection
	peerConnection, err := webrtc.NewAPI(webrtc.WithMediaEngine(m), webrtc.WithInterceptorRegistry(i)).NewPeerConnection(peerConnectionConfig)
	if err != nil {
		panic(err)
	}
	defer func() {
		if cErr := peerConnection.Close(); cErr != nil {
			fmt.Printf("cannot close peerConnection: %v\n", cErr)
		}
	}()

	// Allow us to receive 1 video track
	if _, err = peerConnection.AddTransceiverFromKind(webrtc.RTPCodecTypeVideo); err != nil {
		panic(err)
	}

	localTrackChan := make(chan *webrtc.TrackLocalStaticRTP)
	// Set a handler for when a new remote track starts, this just distributes all our packets
	// to connected peers
	peerConnection.OnTrack(func(remoteTrack *webrtc.TrackRemote, receiver *webrtc.RTPReceiver) {
		// Create a local track, all our SFU clients will be fed via this track
		localTrack, newTrackErr := webrtc.NewTrackLocalStaticRTP(remoteTrack.Codec().RTPCodecCapability, "video", "pion")
		if newTrackErr != nil {
			panic(newTrackErr)
		}
		localTrackChan <- localTrack

		rtpBuf := make([]byte, 1400)
		for {
			i, _, readErr := remoteTrack.Read(rtpBuf)
			if readErr != nil {
				panic(readErr)
			}

			// ErrClosedPipe means we don't have any subscribers, this is ok if no peers have connected yet
			if _, err = localTrack.Write(rtpBuf[:i]); err != nil && !errors.Is(err, io.ErrClosedPipe) {
				panic(err)
			}
		}
	})

	// Set the remote SessionDescription
	err = peerConnection.SetRemoteDescription(offer)
	if err != nil {
		panic(err)
	}

	// Create answer
	answer, err := peerConnection.CreateAnswer(nil)
	if err != nil {
		panic(err)
	}

	// Create channel that is blocked until ICE Gathering is complete
	gatherComplete := webrtc.GatheringCompletePromise(peerConnection)

	// Sets the LocalDescription, and starts our UDP listeners
	err = peerConnection.SetLocalDescription(answer)
	if err != nil {
		panic(err)
	}

	// Block until ICE Gathering is complete, disabling trickle ICE
	// we do this because we only can exchange one signaling message
	// in a production application you should exchange ICE Candidates via OnICECandidate
	<-gatherComplete

	// Get the LocalDescription and take it to base64 so we can paste in browser
	fmt.Println(1)
	fmt.Println(signal.Encode(*peerConnection.LocalDescription()))

	localTrack := <-localTrackChan
	for {
		fmt.Println("")
		fmt.Println("Curl an base64 SDP to start sendonly peer connection")

		recvOnlyOffer := webrtc.SessionDescription{}
		signal.Decode(requestData, &recvOnlyOffer)

		// Create a new PeerConnection
		peerConnection, err := webrtc.NewPeerConnection(peerConnectionConfig)
		if err != nil {
			panic(err)
		}

		rtpSender, err := peerConnection.AddTrack(localTrack)
		if err != nil {
			panic(err)
		}

		// Read incoming RTCP packets
		// Before these packets are returned they are processed by interceptors. For things
		// like NACK this needs to be called.
		go func() {
			rtcpBuf := make([]byte, 1500)
			for {
				if _, _, rtcpErr := rtpSender.Read(rtcpBuf); rtcpErr != nil {
					return
				}
			}
		}()

		// Set the remote SessionDescription
		err = peerConnection.SetRemoteDescription(recvOnlyOffer)
		if err != nil {
			panic(err)
		}

		// Create answer
		answer, err := peerConnection.CreateAnswer(nil)
		if err != nil {
			panic(err)
		}

		// Create channel that is blocked until ICE Gathering is complete
		gatherComplete = webrtc.GatheringCompletePromise(peerConnection)

		// Sets the LocalDescription, and starts our UDP listeners
		err = peerConnection.SetLocalDescription(answer)
		if err != nil {
			panic(err)
		}

		// Block until ICE Gathering is complete, disabling trickle ICE
		// we do this because we only can exchange one signaling message
		// in a production application you should exchange ICE Candidates via OnICECandidate
		<-gatherComplete

		// Get the LocalDescription and take it to base64 so we can paste in browser
		fmt.Println(2)
		fmt.Println(signal.Encode(*peerConnection.LocalDescription()))
	}
}
